# Default values (can be overridden via CLI)

tarfiles: 
  T20: /home/mliu366/scratch/1_in_progress/histo2mri/exvivo_15T/T20.tar

n_channels: 2 #for complex coil data

#for mp2rage denoising
beta: 20000

modules: ["mp2rage", 'dwi', 'mtsat']
